let
    // ============================================================================
    // POLARIS INSIGHTS API MODULE
    // ============================================================================
    // This module contains functions for querying Polaris insights from Jira Product Discovery
    
    // Main function: Get all Polaris insights for a list of issues in a project
    GetPolarisInsightsForIssues = (
        projectAri as text,
        issueIds as list,
        accessToken as text,
        optional includeSnippets as logical
    ) as table =>
        let
            validIssueIds = if issueIds = null or List.IsEmpty(issueIds) then
                {}
            else
                issueIds,
            
            includeSnippets_actual = if includeSnippets = null then true else includeSnippets,
            
            // Function to query insights for a single issue
            QuerySingleIssueInsights = (issueId as text, optional Ari as text, optional includeSnippet as logical, optional token as text) =>
                let
                    // Build the container ARI for the specific issue
                    containerAri = Text.BeforeDelimiter(projectAri, ":project/") & ":issue/" & issueId,
                    
                    query = "
                        query getPolarisInsights($project: ID!, $container: ID) {
                            polarisInsights(project: $project, container: $container) {
                                id
                                description
                                created
                                updated
                                " & (if includeSnippets_actual then "snippets {
                                    id
                                    data
                                    url
                                    properties
                                }" else "") & "
                            }
                        }
                    ",
                    
                    variables = [
                        project = projectAri,
                        container = containerAri
                    ],
                    
                    response = Web.Contents(
                        "https://api-private.atlassian.com/graphql",
                        [
                            Content = Json.FromValue([query=query, variables=variables]),
                            Headers = [
                                Authorization = "Bearer " & accessToken,
                                #"Content-Type" = "application/json",
                                #"X-ExperimentalApi" = "polaris-v0"
                            ],
                            ManualCredentials = true
                        ]
                    ),
                    
                    json = Json.Document(response),
                    hasErrors = Record.HasFields(json, "errors"),
                    
                    // Extract insights or error data
                    insightsData =
                        if hasErrors then
                            {}
                        else if not Record.HasFields(json, "data") then
                            {}
                        else if json[data] = null then
                            {}
                        else if not Record.HasFields(json[data], "polarisInsights") then
                            {}
                        else 
                            let
                                rawInsights = json[data][polarisInsights]
                            in
                                if rawInsights = null then {} else rawInsights,

                    safeInsightsData =
                        if Value.Is(insightsData, List.Type) then
                            insightsData
                        else
                            {},

                    // Add metadata: issue ID and result status
                    withMetadata = List.Transform(
                        safeInsightsData,
                        each _ & [
                            IssueId = issueId,
                            HasError = hasErrors,
                            ErrorMessage = if hasErrors then 
                                try json[errors]{0}[message] otherwise "Unknown error"
                            else
                                null
                        ]
                    )
                in
                    withMetadata,
            
            //Query all issues and combine results
            allInsightsResults =
                if List.IsEmpty(validIssueIds)
                then {}
                else
                    List.Combine(
                        List.Transform(validIssueIds, each QuerySingleIssueInsights(_))
                    ),

            // Convert to table
            outputTable =
                if List.IsEmpty(allInsightsResults)
                then
                    #table(
                        {"id", "description", "created", "updated", "snippets", "IssueId", "HasError", "ErrorMessage"},
                        {}
                    )
                else
                    let
                        tbl = Table.FromRecords(allInsightsResults),
                        //filter out issues with no insights
                        filterNullRows = Table.SelectRows(tbl, each [description] <> null)
                    in
                        filterNullRows
        in
            outputTable,
    
    // Function: Get insights for all JPD projects and create navigation structure
    GetAllPolarisInsights = (
        projectsTable as table,
        cloudId as text,
        accessToken as text
    ) as record =>
        let
            // Function to process a single JPD project
            ProcessJPDProject = (projectRow as record) =>
                let
                    projectId = projectRow[id],
                    projectKey = projectRow[key],
                    projectName = projectRow[name],
                    projectAri = "ari:cloud:jira:" & cloudId & ":project/" & Text.From(projectId),
                    
                    // Get issues for this project
                    issuesTable =
                        if Record.HasFields(projectRow, "Issues") and projectRow[Issues] <> null
                        then projectRow[Issues]
                        else #table({"id"}, {}),

                    issueIds = 
                        if Table.RowCount(issuesTable) = 0 then
                            {}
                        else if Table.HasColumns(issuesTable, "id") then
                            List.Transform(
                                Table.Column(issuesTable, "id"),
                                each Text.From(_)
                            )
                        else {},

                    recordParameters = 
                        [
                            ARI = projectAri,
                            Issues = issueIds,
                            Creds = accessToken
                        ],
                    // Query insights
                    insightsTable =
                        if List.IsEmpty(issueIds)
                        then
                            #table(
                                {"id", "description", "created", "updated", "snippets", "IssueId", "HasError", "ErrorMessage"},
                                {}
                            )
                        else 
                            GetPolarisInsightsForIssues(
                                projectAri,
                                issueIds,
                                accessToken,
                                true
                            ),
                    
                    // Add project context columns
                    withProjectContext = Table.AddColumn(
                        insightsTable,
                        "ProjectId",
                        each projectId,
                        type text
                    ),
                    withProjectKey = Table.AddColumn(
                        withProjectContext,
                        "ProjectKey",
                        each projectKey,
                        type text
                    ),
                    withProjectName = Table.AddColumn(
                        withProjectKey,
                        "ProjectName",
                        each projectName,
                        type text
                    ),
                    withProjectAri = Table.AddColumn(
                        withProjectName,
                        "ProjectAri", each projectAri,
                        type text
                    ),
                    
                    // Create summary stats
                    totalInsights = Table.RowCount(withProjectAri),
                    issuesWithInsights =
                        if totalInsights = 0
                        then 0
                        else
                            List.Count(
                                List.Distinct(
                                    Table.Column(withProjectAri, "IssueId")
                                )
                            ),
                    
                    summaryRecord = [
                        ProjectKey = projectKey,
                        ProjectName = projectName,
                        TotalInsights = totalInsights,
                        IssuesWithInsights = issuesWithInsights,
                        InsightsTable = withProjectContext,
                        LastRefreshed = DateTime.LocalNow()
                    ]
                in
                    //[InsightsTbl = insightsTable],
                    summaryRecord,
            
            // Process all JPD projects
            allProjectInsights = List.Transform(
                Table.ToRecords(projectsTable),
                each ProcessJPDProject(_)
            ),
            
            // Create navigation table with summary info
            navigationRecords = List.Transform(
                allProjectInsights,
                each (
                    let
                        rec = _
                    in
                        [
                            ProjectKey = rec[ProjectKey],
                            ProjectName = rec[ProjectName],
                            TotalInsights = rec[TotalInsights],
                            IssuesWithInsights = rec[IssuesWithInsights],
                            LastRefreshed = rec[LastRefreshed]
                        ]
                )
            ),
            
            navigationTable = if List.IsEmpty(navigationRecords) then
                #table(
                    {"ProjectKey", "ProjectName", "TotalInsights", "IssuesWithInsights", "LastRefreshed"},
                    {}
                )
            else
                Table.FromRecords(navigationRecords),
            
            // Create result record with navigation and individual project tables
            result = [
                NavigationTable = navigationTable,
                ProjectsInsights = Record.FromList(
                    allProjectInsights,
                    List.Transform(
                        allProjectInsights,
                        each [ProjectKey]
                    )
                )
            ]
        in
            //[insghts = allProjectInsights],
            result,
    
    // Error handling wrapper
    SafeGetAllPolarisInsights = (
        projectsTable as table,
        cloudId as text,
        accessToken as text
    ) =>
        let
            attempt = GetAllPolarisInsights(projectsTable, cloudId, accessToken),
        //currently bypassed
            result =
                if attempt[HasError] then
                    [
                        NavigationTable = #table(
                            {"Error", "Details"},
                            {
                                {"Failed to retrieve Polaris insights", attempt[Message] & " (" & attempt[Reason] & ")"}
                            }
                        ),
                        ProjectsInsights = null
                    ]
                else
                    attempt[Value]
        in
            attempt
            //result

in
    [
        SafeGetAllPolarisInsights = SafeGetAllPolarisInsights
    ]
